repository: adrienjoly/adrienjoly.github.com

# github defaults
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# additional config
exclude:
  - resume/node_modules
  - Gemfile
  - Gemfile.lock
