# Name of your blog (this will show up at the top of your page and in the RSS feed)
title: Adrien Joly

# Your name, as you want it to appear underneath each post and in the footer
author: Adrien Joly

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /img/photo.jpg

repository: adrienjoly/adrienjoly.github.com

google_analytics: UA-1858235-4

# github defaults
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# additional config
exclude:
  - resume/node_modules
  - Gemfile
  - Gemfile.lock
